apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app.kubernetes.io/name: minio
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: http-console
      port: 9001
      targetPort: http-console
