apiVersion: v1
kind: ConfigMap
metadata:
  name: app-service-a-nginx-templates
data:
  default.conf.template: |
    server {
      listen 80;
      default_type 'application/json';
      return 200 '{"app": "service-a", "hostname": "$HOSTNAME"}';
    }
