---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: normal
spec:
  replicas: 10
  selector:
    matchLabels:
      app: normal
  template:
    metadata:
      labels:
        app: normal
    spec:
      containers:
        - name: alpine
          image: "alpine:3.15"
          command: ["sleep", "infinity"]
      priorityClassName: normal
