---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: high
spec:
  replicas: 10
  selector:
    matchLabels:
      app: high
  template:
    metadata:
      labels:
        app: high
    spec:
      containers:
        - name: alpine
          image: "alpine:3.15"
          command: ["sleep", "infinity"]
      priorityClassName: normal
