apiVersion: v1
kind: Secret
metadata:
  name: app-example-credentials-john-doe
data:
  kongCredType: YmFzaWMtYXV0aA== # basic-auth
  username: am9obi5kb2U= # john.doe
  password: bXktcGFzc3dvcmQ= # my-password
