apiVersion: v1
kind: ConfigMap
metadata:
  name: app-example-scale-bin
  labels:
    app.kubernetes.io/name: app-example
data:
  scale.sh: |
    #!/usr/bin/env sh
    set -xe
    date
    apk add --quiet curl jq

    curl https://kubernetes.default.svc/openapi/v2 \
      --silent \
      --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
      --header "Authorization: Bearer `cat /var/run/secrets/kubernetes.io/serviceaccount/token`" \
      | jq --raw-output '.info.version | capture("^(?<version>[^+]+)") | .version'
