apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-example-scale
  labels:
    app.kubernetes.io/name: app-example
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-example-scale
subjects:
  - kind: ServiceAccount
    name: app-example-scale
