---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: app-example
      app.kubernetes.io/subset: default
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-example
        app.kubernetes.io/subset: default
    spec:
      containers:
        - name: nginx
          image: nginx:1.23
          ports:
            - name: http
              containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-example-canary
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: app-example
      app.kubernetes.io/subset: canary
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-example
        app.kubernetes.io/subset: canary
    spec:
      containers:
        - name: nginx
          image: nginx:1.23
          ports:
            - name: http
              containerPort: 80
