apiVersion: v1
kind: Service
metadata:
  name: app-example
spec:
  selector:
    app.kubernetes.io/name: app-example
  ports:
    - name: http
      port: 80
      targetPort: http

---

apiVersion: v1
kind: Service
metadata:
  name: app-example-default
spec:
  selector:
    app.kubernetes.io/name: app-example
    app.istio.io/subset: default
  ports:
    - name: http
      port: 80
      targetPort: http

---

apiVersion: v1
kind: Service
metadata:
  name: app-example-canary
spec:
  selector:
    app.kubernetes.io/name: app-example
    app.istio.io/subset: canary
  ports:
    - name: http
      port: 80
      targetPort: http
