apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: app-example
spec:
  hosts:
    - app-example
  http:
    - route:
        - weight: 100
          destination:
            host: app-example
            subset: default
        - weight: 0
          destination:
            host: app-example
            subset: canary
