namespace: reloader

bases:
  - https://github.com/stakater/Reloader/deployments/kubernetes

resources:
  - namespace.yaml
  - deployment.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: entrypoint
    files:
      - assets/entrypoint.sh
