apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: drone-runner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: drone-runner
    spec:
      containers:
        - name: drone-runner
          image: drone/drone-runner-kube
          ports:
            - name: rpc
              containerPort: 3000
          env:
            - name: DRONE_RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone
                  key: DRONE_RPC_SECRET
            - name: DRONE_RPC_HOST
              value: drone
            - name: DRONE_RPC_PROTO
              value: http
            - name: DRONE_DEBUG
              value: "true"
            - name: DRONE_NAMESPACE_DEFAULT
              value: drone
      serviceAccountName: drone-runner
