apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: drone
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: drone
subjects:
  - kind: ServiceAccount
    namespace: drone
    name: default
