apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: drone
spec:
  serviceName: drone
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: drone
  template:
    metadata:
      labels:
        app.kubernetes.io/name: drone
    spec:
      containers:
        - name: drone
          image: drone/drone:2.12
          ports:
            - name: http
              containerPort: 80
          env:
            - name: DRONE_GOGS_SERVER
              valueFrom:
                secretKeyRef:
                  name: drone
                  key: DRONE_GOGS_SERVER
            - name: DRONE_RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone
                  key: DRONE_RPC_SECRET
            - name: DRONE_SERVER_HOST
              value: drone.drone
            - name: DRONE_SERVER_PROTO
              value: http
            - name: DRONE_LOGS_DEBUG
              value: "true"
          volumeMounts:
            - name: drone-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: drone-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
