apiVersion: v1
kind: ConfigMap
metadata:
  name: app-example-bin
data:
  entrypoint.sh: |
    #!/usr/bin/env sh
    trap exit 1 2 15
    date
    apk add --quiet curl jq
    set -xe

    CLUSTER_VERSION=`mktemp`

    curl https://kubernetes.default.svc/openapi/v2 \
      --silent \
      --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
      --header "Authorization: Bearer `cat /var/run/secrets/kubernetes.io/serviceaccount/token`" \
      | jq '.info.version | capture("^(?<version>[^+]+)")' \
      | jq --raw-output '.version' > "$CLUSTER_VERSION"

    curl "https://dl.k8s.io/release/`cat $CLUSTER_VERSION`/bin/linux/amd64/kubectl" \
      --silent --location \
      --output /usr/bin/kubectl

    chmod +x /usr/bin/kubectl

    kubectl version --short

    kubectl config set-cluster my-cluster \
      --server https://kubernetes.default.svc \
      --certificate-authority /app/credentials/ca.crt

    kubectl config set-credentials myself \
      --token `cat /app/credentials/token`

    kubectl config set-context my-context \
      --cluster my-cluster \
      --user myself

    kubectl config use-context my-context

    kubectl get pods \
      --namespace app-example

    sleep infinity &
    wait $!
