apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-example
  labels:
    app.kubernetes.io/name: app-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-example
    spec:
      containers:
        - name: alpine
          image: alpine:3.15
          command:
            - entrypoint.sh
          workingDir: /app
          volumeMounts:
            - name: bin
              mountPath: /usr/local/bin
            - name: credentials
              mountPath: /app/credentials
      volumes:
        - name: bin
          configMap:
            name: app-example-bin
            defaultMode: 0777
        - name: credentials
          secret:
            secretName: app-example-credentials
