apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-example
  labels:
    app.kubernetes.io/name: app-example
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
