apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-example
spec:
  replicas: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: app-example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-example
    spec:
      containers:
        - name: alpine
          image: alpine:3.16
          command:
            - entrypoint.sh
          volumeMounts:
            - name: bin
              mountPath: /usr/local/bin
      volumes:
        - name: bin
          configMap:
            name: app-example-bin
            defaultMode: 0777
