generatorOptions:
  disableNameSuffixHash: true

namespace: app-example

configMapGenerator:
  - name: app-example-bin
    files:
      - assets/entrypoint.sh

resources:
  - deployment.yaml
  - namespace.yaml
