namespace: prometheus

resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - namespace.yaml
  - deployment.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: config
    files:
      - assets/prometheus.yml
