apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
spec:
  namespaceSelector:
    matchNames:
      - prometheus
  selector:
    matchLabels:
      operated-prometheus: "true"
  endpoints:
    - port: web
      interval: 10s
