apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: my-binding
spec:
  vhost: my-vhost
  source: my-exchange
  destination: my-queue
  destinationType: queue
  rabbitmqClusterReference:
    name: hello-world
