version: "3.8"

services:

  app-example:
    image: "node:16.16-alpine"
    volumes:
      - ".:/app"
    working_dir: "/app"
    user: "${UID:-1000}:${GID:-1000}"
    entrypoint: ["npm"]
    command: ["start"]
