apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
spec:
  valuesContent: |-
    additionalArguments:
      - "--log.level=DEBUG"
      # - "--serversTransport.insecureSkipVerify=true"
    ports:
      traefik:
        expose: true
