apiVersion: apps/v1
kind: Deployment
metadata:
  name: store
spec:
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
        - name: nginx
          image: nginx:1.21-alpine
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: nginx-templates
              mountPath: /etc/nginx/templates
            - name: nginx-htpasswd
              mountPath: /etc/nginx/htpasswd
              subPath: htpasswd
            - name: nginx-html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-templates
          configMap:
            name: store-nginx-templates
        - name: nginx-htpasswd
          secret:
            secretName: store-nginx-htpasswd
        - name: nginx-html
          configMap:
            name: store-nginx-html
