namespace: my-secrets-store

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: store-nginx-templates
    files:
      - assets/default.conf.template
  - name: store-nginx-html
    files:
      - assets/env.json

secretGenerator:
  - name: store-nginx-htpasswd
    files:
      - assets/htpasswd
