apiVersion: v1
kind: ConfigMap
metadata:
  name: app-proxy-nginx-templates
data:
  default.conf.template: |
    server {
      listen 80;
      location / {
        add_header 'App-Proxy' '$HOSTNAME';
        proxy_pass http://app-service.app-service;
      }
    }
  status.conf.template: |
    server {
      listen 8080;
      location / {
        stub_status on;
      }
    }
