apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: my-secret-store
spec:
  provider:
    webhook:
      url: http://store.my-secrets-store.svc/env.json
      result:
        jsonPath: $
      headers:
        # admin:102030
        Authorization: Basic YWRtaW46MTAyMDMw
