apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: env
spec:
  refreshInterval: 5s
  secretStoreRef:
    name: my-secret-store
    kind: ClusterSecretStore
  target:
    name: env
  dataFrom:
    - extract:
        key: env # Identifier
