apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: hello-world
  annotations:
    rabbitmq.com/topology-allowed-namespaces: "*"
spec:
  replicas: 3
  resources:
    requests:
      memory: 512M
    limits:
      memory: 512M
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: "kubernetes.io/hostname"
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: hello-world
