---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
    - name: mongodb
      port: 27017
      targetPort: mongodb
  selector:
    name: mongodb

---

apiVersion: v1
kind: Service
metadata:
  name: express
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    name: express
