---

apiVersion: v1
kind: ConfigMap
metadata:
  name: server-templates
data:
  default.conf.template: |
    server {
      listen ${NGINX_PORT};

      location / {
        default_type application/json;
        return 200 '{"name": "${HOSTNAME}"}';
      }
    }

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cache-templates
data:
  default.conf.template: |
    server {
      listen ${NGINX_PORT};

      location / {
        add_header X-Cache-Name "${HOSTNAME}";
        proxy_pass http://server;
      }
    }
