apiVersion: batch/v1
kind: Job
metadata:
  name: ping
spec:
  template:
    spec:
      containers:
        - name: alpine
          image: alpine:3.16
          command: ["ping", "-c5", "1.1.1.1"]
      restartPolicy: Never
