apiVersion: batch/v1
kind: Job
metadata:
  name: crawler
spec:
  template:
    spec:
      containers:
        - name: alpine
          image: alpine:3.16
          command: ["wget", "-q", "https://httpbin.org/anything", "-O-"]
      restartPolicy: Never
