---

apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app.kubernetes.io/name: server
  ports:
    - name: http
      port: 80
      targetPort: http

---

apiVersion: v1
kind: Service
metadata:
  name: cache
spec:
  selector:
    app.kubernetes.io/name: cache
  ports:
    - name: http
      port: 80
      targetPort: http
