apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cache
spec:
  serviceName: cache
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: cache
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cache
    spec:
      containers:
        - name: nginx
          image: nginx:1.21
          ports:
            - name: http
              containerPort: 80
          env:
            - name: NGINX_PORT
              value: "80"
          volumeMounts:
            - name: templates
              mountPath: /etc/nginx/templates
            - name: cache
              mountPath: /var/cache/nginx
      volumes:
        - name: templates
          configMap:
            name: cache-templates
  volumeClaimTemplates:
    - metadata:
        name: cache
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
