---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-requests-cpu
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/resources: requests
      app.kubernetes.io/requests: cpu
  template:
    metadata:
      labels:
        app.kubernetes.io/resources: requests
        app.kubernetes.io/requests: cpu
    spec:
      containers:
        - name: node
          image: node:16.16-alpine
          workingDir: /app
          command: ["node"]
          args: ["server.js", "cpu"]
          resources:
            requests:
              cpu: 750m
          volumeMounts:
            - name: server
              mountPath: /app
      volumes:
        - name: server
          configMap:
            name: resources-server
      nodeSelector:
        node.kubernetes.io/example: resources
      tolerations:
        - key: node.kubernetes.io/example
          operator: Equal
          value: resources
          effect: NoSchedule

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-requests-memory
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/resources: requests
      app.kubernetes.io/requests: memory
  template:
    metadata:
      labels:
        app.kubernetes.io/resources: requests
        app.kubernetes.io/requests: memory
    spec:
      containers:
        - name: node
          image: node:16.16-alpine
          workingDir: /app
          command: ["node"]
          args: ["server.js", "memory"]
          resources:
            requests:
              memory: 768M
          volumeMounts:
            - name: server
              mountPath: /app
      volumes:
        - name: server
          configMap:
            name: resources-server
      nodeSelector:
        node.kubernetes.io/example: resources
      tolerations:
        - key: node.kubernetes.io/example
          operator: Equal
          value: resources
          effect: NoSchedule
