apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: webserver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webserver
    spec:
      containers:
        - name: nginx
          image: nginx:1.23
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: 512M
      nodeSelector:
        node.kubernetes.io/example: resources
      tolerations:
        - key: node.kubernetes.io/example
          operator: Equal
          value: resources
          effect: NoSchedule
