---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-requests-cpu
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/resources: requests
      app.kubernetes.io/requests: cpu
  template:
    metadata:
      labels:
        app.kubernetes.io/resources: requests
        app.kubernetes.io/requests: cpu
    spec:
      containers:
        - name: nginx
          image: nginx:1.23
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 750m
      nodeSelector:
        node.kubernetes.io/example: resources
      tolerations:
        - key: node.kubernetes.io/example
          operator: Equal
          value: resources
          effect: NoSchedule

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-requests-memory
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/resources: requests
      app.kubernetes.io/requests: memory
  template:
    metadata:
      labels:
        app.kubernetes.io/resources: requests
        app.kubernetes.io/requests: memory
    spec:
      containers:
        - name: nginx
          image: nginx:1.23
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: 768M
      nodeSelector:
        node.kubernetes.io/example: resources
      tolerations:
        - key: node.kubernetes.io/example
          operator: Equal
          value: resources
          effect: NoSchedule
