version: "3.8"

services:

  app-factorial-api:
    image: "node:16.16-alpine"
    volumes:
      - ".:/app"
    networks:
      - "app-services"
      - "app-factorial-worker"
    working_dir: "/app"
    user: "${UID:-1000}:${GID:-1000}"
    entrypoint: ["npm"]
    command: ["start"]
    environment:
      # AWS
      AWS_ENDPOINT: "http://minio:9000"
      AWS_ACCESS_KEY_ID: "AKIAIOSFODNN7EXAMPLE"
      AWS_SECRET_ACCESS_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
      AWS_BUCKET: "app-factorial-api"
      # RabbitMQ
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
      RABBITMQ_USERNAME: "admin"
      RABBITMQ_PASSWORD: "admin"
      RABBITMQ_QUEUE: "app-factorial-worker"
      # Local
      PORT: "3000"

networks:
  app-services:
    name: "app-services"
    external: true
  app-factorial-worker:
    name: "app-factorial-worker"
