apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: app-factorial-worker
spec:
  vhost: /
  source: app-factorial-api
  routingKey: factorial
  destination: app-factorial-worker
  destinationType: queue
  rabbitmqClusterReference:
    namespace: rabbitmq
    name: rabbitmq
