apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: app-factorial-worker
spec:
  vhost: /
  userReference:
    name: app-factorial-worker
  permissions:
    write: "^$"
    read: "^app-factorial-worker$"
    configure: "^$"
  rabbitmqClusterReference:
    namespace: rabbitmq
    name: rabbitmq
