apiVersion: v1
kind: ConfigMap
metadata:
  name: template
data:
  default.conf.template: |
    server {
      listen ${APP_PORT};
      location / {
        auth_basic 'Application Realm';
        auth_basic_user_file '/etc/nginx/auth/htpasswd';
        try_files DUMMY @return200; # workaround
      }
      location @return200 {
        add_header Content-Type 'application/json;charset=utf-8';
        return 200 '{"name":"${APP_NAME}"}';
      }
    }
