apiVersion: v1
kind: Secret
metadata:
  name: minio-env
data:
  MINIO_ROOT_USER: QUtJQUlPU0ZPRE5ON0VYQU1QTEU= # AKIAIOSFODNN7EXAMPLE
  MINIO_ROOT_PASSWORD: d0phbHJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ== # wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
