apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: console
      port: 9001
      targetPort: console
  selector:
    name: minio
