apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: app-factorial-api
spec:
  vhost: /
  userReference:
    name: app-factorial-api
  permissions:
    write: "^app-factorial-api$"
    read: "^$"
    configure: "^$"
  rabbitmqClusterReference:
    namespace: rabbitmq
    name: rabbitmq
