---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: high
spec:
  replicas: 2
  selector:
    matchLabels:
      app: high
  template:
    metadata:
      labels:
        app: high
    spec:
      containers:
        - name: alpine
          image: "alpine:3.15"
          command: ["sleep", "infinity"]
          resources:
            requests:
              memory: "512M"
            limits:
              memory: "512M"
      priorityClassName: normal
