namespace: debug

resources:
  - namespace.yaml
  - deployment.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: entrypoint
    files:
      - assets/entrypoint.sh

secretGenerator:
  - name: debug
    envs:
      - .env
