apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca
spec:
  isCA: true
  commonName: root-ca
  secretName: root-ca
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    kind: Issuer
    name: self-signed

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example
spec:
  commonName: example
  secretName: example-certificate
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    kind: Issuer
    name: root-ca
