apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca
spec:
  isCA: true
  commonName: root-ca
  secretName: root-ca
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    kind: Issuer
    name: self-signed
