apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: crawler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: crawler
    spec:
      containers:
        - name: alpine
          image: alpine:3.16
          command: ["/usr/local/bin/entrypoint.sh"]
          volumeMounts:
            - name: bin
              mountPath: /usr/local/bin
            - name: certificate
              mountPath: /etc/ssl/root-ca
      volumes:
        - name: certificate
          secret:
            secretName: root-ca
            items:
              - key: ca.crt
                path: ca.crt
        - name: bin
          configMap:
            name: crawler-bin
            defaultMode: 0777
